Models iniciais, trabalho iniciado
TreinaDev/esperto-fit-promocoes pull request #1
Opened 2020-09-28 20:25 UTC by Murimaral

Co-authored-by: Alexandre <alexandre.alpe@gmail.com>
Co-authored-by: Luisa <luludila@gmail.com>
Co-authored-by: Eduardo <gris.eduardo@gmail.com>

2020-09-28 21:17 UTC, joaorsalmeida commented on app/models/model.rb
> +class Model < ApplicationRecord
Esse nome definitivamente não vai funcionar bem. O que significa?

2020-09-28 21:18 UTC, joaorsalmeida commented on app/models/customer_cpf.rb
> +class CustomerCpf < ApplicationRecord
`CustomerCpf` é um nome bem específico para um `model` não? Me parece que esse seria o funcionário de uma empresa parceira né?

2020-09-28 21:18 UTC, joaorsalmeida requested changes
Deixei alguns comentários, acho que vale a pena revisar e pensar com mais calma o  nome de alguns models ^^

2020-09-28 22:26 UTC, Murimaral commented on app/models/model.rb
> +class Model < ApplicationRecord
Acabamos errando na linha de comando, sem querer demos o nome de model (acabou saindo um model chamado model com atributo user). Vamos corrigir!

2020-09-28 22:30 UTC, Murimaral commented on app/models/customer_cpf.rb
> +class CustomerCpf < ApplicationRecord
Discutimos sobre esse nome de model por um tempo e nao estamos 100% satisfeitos mesmo. Para prosseguir na criação, deixamos assim por hora. A ideia desse model é amarrar o lote de CPFs de uma empresa parceira. (Company has_many customer_cpfs;  customer_cpf has_one company).

2020-09-28 23:05 UTC, luisalandert commented on app/models/customer_cpf.rb
> +class CustomerCpf < ApplicationRecord
A gente tinha pensado em usar so cpf mas depois mudamos para esse, será que seria melhor deixar só cpf já q os outros sistemas vão consumir APIs relacionadas a esse model?

2020-09-29 16:27 UTC, joaorsalmeida commented on app/models/customer_cpf.rb
> +class CustomerCpf < ApplicationRecord
Se esse model representa um funcionar de uma empresa parceira, minha sugestão seria: PartnerEmployee para ele e PartnerCompany para a empresa. Que tal?

2020-09-29 16:35 UTC, joaorsalmeida commented
Sobre o model `Model`, vi que renomearam os arquivos. Não sei se é uma boa. Me parece que o melhor seria fazer um `rails destroy` e depois outro `generate`.

2020-09-29 18:50 UTC, closed without merging