WIP Cadastra CPF de funcionario de empresa parceira
TreinaDev/esperto-fit-promocoes pull request #13
Opened 2020-10-02 19:27 UTC by Alexandre-Luiz

Co-authored-by: Luisa <luludila@gmail.com>

Cadastro de CPF de funcionário de empresa parceira a partir de um arquivo txt.

TO DO:
- Validação arquivo vazio
- Validação CPF válido
- Validação formato do arquivo
- Validação se CPF já cadastrado

Fix #6

2020-10-05 18:14 UTC, joaorsalmeida commented
Muito bom pessoal! 

Senti falta de dois cenários de teste: 

- CPFs duplicados (pode ser no mesmo arquivo mas também pode ser um CPF já cadasrado que vem novamente em um arquivo). 
- CPFs duplicados em empresas diferentes (O que acontece se a mesma pessoa tem vínculo com 2 empresas? Será que deveríamos permitir? Talvez esse cenário mereça virar uma nova issue)

2020-10-05 18:15 UTC, joaorsalmeida commented on app/controllers/partner_company_employees_controller.rb
> +    @partner_company = PartnerCompany.find(params[:partner_company_id])
Essa lógica ficou muito grande para um controller. Minha dica inicial: obtenham o conteúdo do arquivo como uma string e passem para um método da classe `PartnerCompany`, por exemplo `PartnerCompany # add_employees`

2020-10-05 18:16 UTC, joaorsalmeida requested changes
Fiz alguns comentários. Acredito que isolar a lógica do controller e adicionar um cenário para CPFs duplicados são importantes para fecharmos esse PR.

2020-10-05 18:24 UTC, luisalandert commented on app/controllers/partner_company_employees_controller.rb
> +    @partner_company = PartnerCompany.find(params[:partner_company_id])
Estavamos na dúvida mesmo como melhorar essa action, essa ideia do método é ótima mesmo

2020-10-05 19:30 UTC, Alexandre-Luiz commented on app/controllers/partner_company_employees_controller.rb
> +    @partner_company = PartnerCompany.find(params[:partner_company_id])
Extraímos a lógica para a classe PartnerCompany para reduzir o controller.

2020-10-06 20:42 UTC, joaorsalmeida approved these changes

2020-10-06 20:43 UTC, merged